# This workflow builds a Java project and deploys it to an Azure Web App when
# changes are pushed to the main branch.
#
# To use this workflow:
# 1. Create the Web App in Azure.
# 2. Add the secret `AZURE_WEBAPP_PUBLISH_PROFILE` to your repository.
# 3. Adjust the variables in the env section as needed.

name: Deploy Java project to Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'your-webapp-name'   # set this to your Web App name
  POM_XML_DIRECTORY: '.'                  # path containing pom.xml
  DISTRIBUTION: 'temurin'                 # e.g. 'zulu', 'temurin', 'microsoft'
  JAVA_VERSION: '17'                      # e.g. '8', '11', '17'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Maven
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn -B package
        popd

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.POM_XML_DIRECTORY }}/target/*.jar
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

